import os

templates_dir = "/home/ayush/Projects/drogon_go/internal/templates"
generator_dir = "/home/ayush/Projects/drogon_go/internal/generator"
os.makedirs(templates_dir, exist_ok=True)
os.makedirs(generator_dir, exist_ok=True)

# Generate Filter Template .tmpl files
with open(f"{templates_dir}/filter_h.tmpl", "w") as f:
    f.write("""/**
 *
 *  {{.FileName}}.h
 *
 */

#pragma once

#include <drogon/HttpFilter.h>
using namespace drogon;
{{if .Namespaces}}{{range .Namespaces}}
namespace {{.}}
{{{end}}{{end}}

class {{.ClassName}} : public HttpFilter<{{.ClassName}}>
{
  public:
    {{.ClassName}}() {}
    void doFilter(const HttpRequestPtr &req,
                  FilterCallback &&fcb,
                  FilterChainCallback &&fccb) override;
};
{{if .Namespaces}}{{range .Namespaces}}
}
{{end}}{{end}}
""")

with open(f"{templates_dir}/filter_cc.tmpl", "w") as f:
    f.write("""/**
 *
 *  {{.FileName}}.cc
 *
 */

#include "{{.FileName}}.h"

{{if .NamespaceString}}using namespace {{.NamespaceString}};{{end}}

void {{.ClassName}}::doFilter(const HttpRequestPtr &req,
                         FilterCallback &&fcb,
                         FilterChainCallback &&fccb)
{
    //Edit your logic here
    if (1)
    {
        //Passed
        fccb();
        return;
    }
    //Check failed
    auto res = drogon::HttpResponse::newHttpResponse();
    res->setStatusCode(k500InternalServerError);
    fcb(res);
}
""")

# Generate Plugin Template .tmpl files
with open(f"{templates_dir}/plugin_h.tmpl", "w") as f:
    f.write("""/**
 *
 *  {{.FileName}}.h
 *
 */

#pragma once

#include <drogon/Plugin.h>
{{if .Namespaces}}{{range .Namespaces}}
namespace {{.}}
{{{end}}{{end}}

class {{.ClassName}} : public drogon::Plugin<{{.ClassName}}>
{
  public:
    {{.ClassName}}() {}
    /// This method must be called by drogon to initialize and start the plugin.
    /// It must be implemented by the user.
    void initAndStart(const Json::Value &config) override;

    /// This method must be called by drogon to shutdown the plugin.
    /// It must be implemented by the user.
    void shutdown() override;
};
{{if .Namespaces}}{{range .Namespaces}}
}
{{end}}{{end}}
""")

with open(f"{templates_dir}/plugin_cc.tmpl", "w") as f:
    f.write("""/**
 *
 *  {{.FileName}}.cc
 *
 */

#include "{{.FileName}}.h"

{{if .NamespaceString}}using namespace {{.NamespaceString}};{{end}}

void {{.ClassName}}::initAndStart(const Json::Value &config)
{
    /// Initialize and start the plugin
}

void {{.ClassName}}::shutdown() 
{
    /// Shutdown the plugin
}
""")

# Restful Controller Templates
with open(f"{templates_dir}/restful_controller_h.tmpl", "w") as f:
    f.write("""/**
 *
 *  {{.FileName}}.h
 *  This file is generated by drogon_ctl
 *
 */

#pragma once

#include <drogon/HttpController.h>
using namespace drogon;
{{if .Namespaces}}{{range .Namespaces}}
namespace {{.}}
{{{end}}{{end}}
/**
 * @brief this class is created by the drogon_ctl command ({{.CtlCommand}}).
 * this class is a restful API controller.
 */
class {{.ClassName}}: public drogon::HttpController<{{.ClassName}}>
{
  public:
    METHOD_LIST_BEGIN
    // use METHOD_ADD to add your custom processing function here;
{{if eq .Resource ""}}    METHOD_ADD({{.ClassName}}::getOne,"/{1}",Get,Options{{.Filters}});
    METHOD_ADD({{.ClassName}}::get,"",Get,Options{{.Filters}});
    METHOD_ADD({{.ClassName}}::create,"",Post,Options{{.Filters}});
    METHOD_ADD({{.ClassName}}::updateOne,"/{1}",Put,Options{{.Filters}});
    //METHOD_ADD({{.ClassName}}::update,"",Put,Options{{.Filters}});
    METHOD_ADD({{.ClassName}}::deleteOne,"/{1}",Delete,Options{{.Filters}});
{{else}}    ADD_METHOD_TO({{.ClassName}}::getOne,"{{.Resource}}/{1}",Get,Options{{.Filters}});
    ADD_METHOD_TO({{.ClassName}}::updateOne,"{{.Resource}}/{1}",Put,Options{{.Filters}});
    ADD_METHOD_TO({{.ClassName}}::deleteOne,"{{.Resource}}/{1}",Delete,Options{{.Filters}});
    ADD_METHOD_TO({{.ClassName}}::get,"{{.Resource}}",Get,Options{{.Filters}});
    ADD_METHOD_TO({{.ClassName}}::create,"{{.Resource}}",Post,Options{{.Filters}});
    //ADD_METHOD_TO({{.ClassName}}::update,"{{.Resource}}",Put,Options{{.Filters}});
{{end}}    METHOD_LIST_END

    void getOne(const HttpRequestPtr &req,
                std::function<void(const HttpResponsePtr &)> &&callback,
                std::string &&id);
    void updateOne(const HttpRequestPtr &req,
                std::function<void(const HttpResponsePtr &)> &&callback,
                std::string &&id);
    void deleteOne(const HttpRequestPtr &req,
                   std::function<void(const HttpResponsePtr &)> &&callback,
                   std::string &&id);
    void get(const HttpRequestPtr &req,
             std::function<void(const HttpResponsePtr &)> &&callback);
    void create(const HttpRequestPtr &req,
                std::function<void(const HttpResponsePtr &)> &&callback);

//    void update(const HttpRequestPtr &req,
//                std::function<void(const HttpResponsePtr &)> &&callback);

};
{{if .Namespaces}}{{range .Namespaces}}
}
{{end}}{{end}}
""")

with open(f"{templates_dir}/restful_controller_cc.tmpl", "w") as f:
    f.write("""/**
 *
 *  {{.FileName}}.cc
 *  This file is generated by drogon_ctl
 *
 */

#include "{{.FileName}}.h"
#include <string>

{{if .NamespaceString}}using namespace {{.NamespaceString}};{{end}}

void {{.ClassName}}::getOne(const HttpRequestPtr &req,
             {{.Indent}}std::function<void(const HttpResponsePtr &)> &&callback,
             {{.Indent}}std::string &&id)
{

}
void {{.ClassName}}::updateOne(const HttpRequestPtr &req,
             {{.Indent}}   std::function<void(const HttpResponsePtr &)> &&callback,
             {{.Indent}}   std::string &&id)
{

}
void {{.ClassName}}::deleteOne(const HttpRequestPtr &req,
             {{.Indent}}   std::function<void(const HttpResponsePtr &)> &&callback,
             {{.Indent}}   std::string &&id)
{

}
void {{.ClassName}}::get(const HttpRequestPtr &req,
             {{.Indent}}std::function<void(const HttpResponsePtr &)> &&callback)
{

}
void {{.ClassName}}::create(const HttpRequestPtr &req,
             {{.Indent}}   std::function<void(const HttpResponsePtr &)> &&callback)
{

}
""")
